# Generated by Django 5.1.6 on 2025-02-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
