# Generated by Django 5.1.6 on 2025-02-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
